"""more columns

Revision ID: 3bfdb38542fa
Revises: 66b51639236d
Create Date: 2023-01-24 17:12:29.527555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfdb38542fa'
down_revision = '66b51639236d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_for_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('purchased_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('purchased_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_products', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('purchased_at')
        batch_op.drop_column('price')

    with op.batch_alter_table('products_for_sale', schema=None) as batch_op:
        batch_op.drop_column('added_at')

    # ### end Alembic commands ###
