"""payment status column

Revision ID: 3e71761ddb8d
Revises: f9725bfd1e48
Create Date: 2023-01-24 12:38:45.432024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e71761ddb8d'
down_revision = 'f9725bfd1e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_products', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
