"""quantity column

Revision ID: 46cfe493939d
Revises: 12f393738fc9
Create Date: 2023-01-22 18:20:54.543344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cfe493939d'
down_revision = '12f393738fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_for_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_for_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.INTEGER(), nullable=False))
        batch_op.drop_column('quantity')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
