"""add vendor id column

Revision ID: 6b162d45dfb6
Revises: 9d117e1b33f9
Create Date: 2023-01-23 14:22:48.932095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b162d45dfb6'
down_revision = '9d117e1b33f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_purchased_products_customer_id_customer'), 'customer', ['customer_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchased_products_customer_id_customer'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['vendor_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
