"""rename customer id column in purchased product model

Revision ID: 9d117e1b33f9
Revises: 4ca4cf9313e8
Create Date: 2023-01-23 14:17:42.705039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d117e1b33f9'
down_revision = '4ca4cf9313e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_purchased_products_customer_id_customer'), 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_purchased_products_customer_id_customer'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['vendor_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
