"""allow status for vendor product

Revision ID: f41ab0b7f503
Revises: 46cfe493939d
Create Date: 2023-01-22 19:35:53.555857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41ab0b7f503'
down_revision = '46cfe493939d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_for_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_for_sale', schema=None) as batch_op:
        batch_op.drop_column('allow_status')

    # ### end Alembic commands ###
