"""more columns purchased product

Revision ID: f9725bfd1e48
Revises: 6b162d45dfb6
Create Date: 2023-01-23 15:37:19.666824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9725bfd1e48'
down_revision = '6b162d45dfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_products', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
